//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Book.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookCopies1 = new HashSet<BookCopy>();
        }
    
        public int ID { get; set; }
        public string BookName { get; set; }
        public string Authors { get; set; }
        public short Year { get; set; }
        public string Category { get; set; }
        public short BookCopies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCopy> BookCopies1 { get; set; }
    }
}
