//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAssistant.Database
{
    using System;
    using System.Collections.Generic;

    public partial class Event : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Completeds = new HashSet<Completed>();
            this.Tasks = new HashSet<Task>();
        }

        public Event(Event obj)
        {
            ID = obj.ID;
            Title = obj.Title;
            Date = obj.Date;
            Description = obj.Description;
            Priority = obj.Priority;
        }

        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Completed> Completeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
